// assemble.mjs — build the CONCEPTS array from the per-concept source of truth.
//
// Source of truth: concepts/<id>/concept.json (+ sibling code files).
// Output: concepts.data.js — a committed bundle `export const CONCEPTS = [...]`
// that concepts.js imports (the SPA needs every concept at load; it can't fetch
// 342 files). CI's drift test (test/assemble.test.mjs) fails if the committed
// bundle ever falls out of sync with the json files.
//
// Run:  node assemble.mjs   (also runs as the first half of `npm run build`)

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = dirname(fileURLToPath(import.meta.url));
const CONCEPTS_DIR = join(ROOT, 'concepts');

// Read every concepts/<id>/concept.json, strip editor-only $-keys, return the
// CONCEPTS array in a deterministic (alphabetical-by-id) order.
export async function assembleConcepts() {
  let entries = [];
  try { entries = await readdir(CONCEPTS_DIR, { withFileTypes: true }); } catch { entries = []; }
  const out = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    let raw;
    try { raw = await readFile(join(CONCEPTS_DIR, e.name, 'concept.json'), 'utf8'); }
    catch { continue; } // a folder with only code files and no metadata — skip
    const obj = JSON.parse(raw);
    for (const k of Object.keys(obj)) if (k.startsWith('$')) delete obj[k]; // drop $schema etc.
    out.push(obj);
  }
  out.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  return out;
}

export function serializeBundle(concepts) {
  return [
    '// GENERATED by assemble.mjs from concepts/<id>/concept.json — do not edit by hand.',
    '// Rebuild with `npm run build` (or `node assemble.mjs`).',
    '// The source of truth is concepts/<id>/concept.json; this committed bundle exists',
    '// so the SPA loads all concepts in one request. A CI drift test keeps them in sync.',
    `export const CONCEPTS = ${JSON.stringify(concepts)};`,
    '',
  ].join('\n');
}

async function main() {
  const concepts = await assembleConcepts();
  await writeFile(join(ROOT, 'concepts.data.js'), serializeBundle(concepts), 'utf8');
  console.log(`Assembled ${concepts.length} concepts → concepts.data.js`);
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) await main();
